[Database]
# URL is the PostgreSQL URI to connect to your database. Chainlink nodes require Postgres versions >= 11. See
# [Running a Chainlink Node](https://docs.chain.link/docs/running-a-chainlink-node/#set-the-remote-database_url-config) for an example.
#
# Environment variable: `CL_DATABASE_URL`
URL = "postgresql://chainlink:chainlink@localhost:5432/chainlink_test?sslmode=disable" # Example
# BackupURL is where the automatic database backup will pull from, rather than the main DATABASE_URL. It is recommended
# to set this value to a read replica if you have one to avoid excessive load on the main database.
#
# Environment variable: `CL_DATABASE_BACKUP_URL`
# BackupURL = "postgresql://user:pass@read-replica.example.com:5432/dbname?sslmode=disable" # Example
# AllowSimplePasswords skips the password complexity check normally enforced on URL & BackupURL.
#
# Environment variable: `CL_DATABASE_ALLOW_SIMPLE_PASSWORDS`
AllowSimplePasswords = false # Default


[Password]
# Keystore is the password for the node's account.
#
# Environment variable: `CL_PASSWORD_KEYSTORE`
Keystore = ";,.pyfgcrl/@aoeu" # Example
# VRF is the password for the vrf keys.
#