# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  wakatime-zsh-plugin = {
    pname = "wakatime-zsh-plugin";
    version = "7b3103d28c89f571111de3586c6ea98f5b26dd70";
    src = fetchgit {
      url = "https://github.com/sobolevn/wakatime-zsh-plugin.git";
      rev = "7b3103d28c89f571111de3586c6ea98f5b26dd70";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-6isB3WWn79hKsUOlX/3yg7XeE0ZrigrXO3nVv4O4tl4=";
    };
    date = "2024-02-12";
  };
}
