# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  alias-tips = {
    pname = "alias-tips";
    version = "41cb143ccc3b8cc444bf20257276cb43275f65c4";
    src = fetchgit {
      url = "https://github.com/djui/alias-tips.git";
      rev = "41cb143ccc3b8cc444bf20257276cb43275f65c4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-ZFWrwcwwwSYP5d8k7Lr/hL3WKAZmgn51Q9hYL3bq9vE=";
    };
    date = "2023-01-19";
  };
  wakatime-zsh-plugin = {
    pname = "wakatime-zsh-plugin";
    version = "7b3103d28c89f571111de3586c6ea98f5b26dd70";
    src = fetchgit {
      url = "https://github.com/sobolevn/wakatime-zsh-plugin.git";
      rev = "7b3103d28c89f571111de3586c6ea98f5b26dd70";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-6isB3WWn79hKsUOlX/3yg7XeE0ZrigrXO3nVv4O4tl4=";
    };
    date = "2024-02-12";
  };
}
