# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, dockerTools }: {
  alias-tips = {
    pname = "alias-tips";
    version = "41cb143ccc3b8cc444bf20257276cb43275f65c4";
    src = fetchgit {
      url = "https://github.com/djui/alias-tips.git";
      rev = "41cb143ccc3b8cc444bf20257276cb43275f65c4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-ZFWrwcwwwSYP5d8k7Lr/hL3WKAZmgn51Q9hYL3bq9vE=";
    };
    date = "2023-01-19";
  };
  wakatime-zsh-plugin = {
    pname = "wakatime-zsh-plugin";
    version = "69c6028b0c8f72e2afcfa5135b1af29afb49764a";
    src = fetchgit {
      url = "https://github.com/sobolevn/wakatime-zsh-plugin.git";
      rev = "69c6028b0c8f72e2afcfa5135b1af29afb49764a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-pA1VOkzbHQjmcI2skzB/OP5pXn8CFUz5Ok/GLC6KKXQ=";
    };
    date = "2022-04-27";
  };
}
