# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, ... }: {
  alias-tips = {
    pname = "alias-tips";
    version = "4d2cf6f10e5080f3273be06b9801e1fd1f25d28d";
    src = fetchgit {
      url = "https://github.com/djui/alias-tips.git";
      rev = "4d2cf6f10e5080f3273be06b9801e1fd1f25d28d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-0N2DCpMraIXtEc7hMp0OBANNuYhHPLqzJ/hrAFcLma8=";
    };
  };
  wakatime-zsh-plugin = {
    pname = "wakatime-zsh-plugin";
    version = "69c6028b0c8f72e2afcfa5135b1af29afb49764a";
    src = fetchgit {
      url = "https://github.com/sobolevn/wakatime-zsh-plugin.git";
      rev = "69c6028b0c8f72e2afcfa5135b1af29afb49764a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-pA1VOkzbHQjmcI2skzB/OP5pXn8CFUz5Ok/GLC6KKXQ=";
    };
  };
}
