#!/bin/zsh

# Load resources

xrdb -merge .Xresources

# Set up an icon tray
stalonetray &

# Fire up apps

xscreensaver -no-splash &

xmodmap ~/.xmodmap

# Set background image with feh
feh --bg-scale /usr/share/backgrounds/warty-final-ubuntu.png &
# Start udiskie to handle media
udiskie &

xfce4-power-manager &

if [ -x /usr/bin/nm-applet ] ; then
   nm-applet --sm-disable &
fi

exec xmonad
