export ZSH=~/.oh-my-zsh

ZSH_THEME="powerlevel9k/powerlevel9k"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir rbenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vi_mode status root_indicator background_jobs history time)

plugins=(react-native tmux git zsh-autosuggestions zsh-syntax-highlighting z)

if [[ "$OSTYPE" == "linux-gnu" ]]; then
    plugins+=(ubuntu)
else [[ "$OSTYPE" == "darwin"* ]];
    plugins+=(osx)
fi

source $ZSH/oh-my-zsh.sh

export LANG=en_US.UTF-8
export TERM="xterm-256color"
bindkey -v
export KEYTIMEOUT=1
source ~/.bash_profile

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
    export EDITOR='vim'
else
    export EDITOR='mvim'
fi

#For easy use code
codi() {
    local syntax="${1:-python}"
    shift
    vim -c \
        "let g:startify_disable_at_vimenter = 1 |\
        set bt=nofile ls=0 noru nonu nornu |\
        hi ColorColumn ctermbg=NONE |\
        hi VertSplit ctermbg=NONE |\
        hi NonText ctermfg=0 |\
        Codi $syntax" "$@"
}

#blow add vi indicator to bar
function zle-line-init {
    powerlevel9k_prepare_prompts
    if (( ${+terminfo[smkx]} )); then
        printf '%s' ${terminfo[smkx]}
    fi
    zle reset-prompt
    zle -R
}

function zle-line-finish {
    powerlevel9k_prepare_prompts
    if (( ${+terminfo[rmkx]} )); then
        printf '%s' ${terminfo[rmkx]}
    fi
    zle reset-prompt
    zle -R
}

function zle-keymap-select {
    powerlevel9k_prepare_prompts
    zle reset-prompt
    zle -R
}

zle -N zle-line-init
zle -N ale-line-finish
zle -N zle-keymap-select
