export ZSH=~/.oh-my-zsh

POWERLEVEL9K_MODE='nerdfont-fontconfig'
POWERLEVEL9K_VCS_SHOW_SUBMODULE_DIRTY=false

if [ -n "$INSIDE_EMACS" ]; then
    export ZSH_THEME="robbyrussell"
else
    export ZSH_THEME="powerlevel9k/powerlevel9k"
  fi

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(disk_usage dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs ram)

plugins=(emacs react-native tmux git zsh-autosuggestions zsh-syntax-highlighting z)
source $ZSH/oh-my-zsh.sh

if [[ "$OSTYPE" == "linux-gnu" ]]; then
    plugins+=(ubuntu)
else [[ "$OSTYPE" == "darwin"* ]];
    plugins+=(osx)
fi


# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
    export EDITOR='vim'
else
    export EDITOR='mvim'
fi
