keys:
  - &xiongchenyu 4EDE451FC10722D0C6662C6FB99B8189C7C153F6
  - &yubikey C0807F4C5201D2EE612EE933D750F82262844F39
  - &office age1ss6yryyyma55atqs9mr823q0s9fqlu9rdh6dmkmzhxq8jvf635qssp5cuw
  - &office-mac age1n8dtlw45h5gh4zp0l53tcasffzgqflyx623ppypasrukyt8kv3vqljflr3
  - &oracle-arm-001 age1xm5qgvpmy6whs5jqrdzde0l33qktg4azst3zpyr7lgg5qh9cqfjs56e7d5
  - &oracle-arm-002 age1ferch3rq8xyvdqmvws8qg247s2uxsjf4pul6430436rg32tchq7q3aj98d
  - &oracle-amd-001 age1gzyuqqta5820q5ve2udpuf9ccdqd3le7rgtcxz8zxa92cv66qp6s46ukq5
  - &oracle-amd-002 age1e705lmnt4g006qpflm8wyefr23papuz3cq5z4dyctjp6u7qz2y0qzmmh5x
  - &mail age14z507h9qugzy65rpfgrzlrzkvyvwsqlwv7nguamaw4wx830hsu0qt23vx3
  - &game age107w29mcnleyvvza8r9p3pkq6v7pqg8y3uvn9vp0pa55yrrwa757ss3xg5x
  - &netbird age19eapwgdt8ufhzztcs84jtqyyymh5ypld39mq3kc48aruz7jmu3gqgysyle
  - &huoshan-bj-001 age13sanuad3fazmechnpya64v7cc4swy4v5u6wks09cqxk45lvlhg9seztxzp

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *office
          - *mail
          - *game
          - *netbird
          - *huoshan-bj-001
          - *oracle-arm-001
          - *oracle-arm-002
          - *oracle-amd-001
          - *oracle-amd-002
          - *office-mac
        pgp:
          - *xiongchenyu
          - *yubikey 
  - path_regex: secrets/[^/]+\.env$
    key_groups:
      - age:
          - *office
          - *mail
          - *game
          - *netbird
          - *huoshan-bj-001
          - *oracle-arm-001
          - *oracle-arm-002 
          - *oracle-amd-001
          - *oracle-amd-002
          - *office-mac
        pgp:
          - *xiongchenyu
          - *yubikey 
