keys:
  - &xiong 40C5 2631 2E36 C3D5 A3E2  6245 F159 84A2 F97A 8554
  - &freeman A3BD 5EAB B004 993E C528  FF55 336D 63C5 7AD5 72AF
  - &office age13t04ywngwwteclx080zmmjef06d9erk3uh3je9tre2dvf2nmv5hql7g5jy
  - &mail age14z507h9qugzy65rpfgrzlrzkvyvwsqlwv7nguamaw4wx830hsu0qt23vx3
  - &digital age1zny9jmahvgqk5470fqdlemhzl5sx9ehcd8gjljg5cf66pqz7d3rqy7vmgg
  - &game age1pl2sjqa46kh3yl44yq4yldvxgfp7cq3jyhuq7rsedz4eedgrxvyqfka6mz

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *office
          - *mail
          - *digital
          - *game
        pgp:
          - *freeman
          - *xiong
