keys:
  - &xiongchenyu 4EDE451FC10722D0C6662C6FB99B8189C7C153F6
  - &office age13t04ywngwwteclx080zmmjef06d9erk3uh3je9tre2dvf2nmv5hql7g5jy
  - &mail age14z507h9qugzy65rpfgrzlrzkvyvwsqlwv7nguamaw4wx830hsu0qt23vx3
  - &game-office age17cz5tfj48gx44ku3j97ptpe4jtrwjtjshwah5uscmg03xv082vas2lhgc8
  - &game age107w29mcnleyvvza8r9p3pkq6v7pqg8y3uvn9vp0pa55yrrwa757ss3xg5x
  - &netbird age19eapwgdt8ufhzztcs84jtqyyymh5ypld39mq3kc48aruz7jmu3gqgysyle
  - &huawei-bj-001 age1ps4yc5vx6ne098pnqc6xw6u6qtah89g6yxz0y8szm54g4untmc4qsgl9me
  - &huoshan-bj-001 age13sanuad3fazmechnpya64v7cc4swy4v5u6wks09cqxk45lvlhg9seztxzp

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *office
          - *mail
          - *game-office
          - *game
          - *netbird
          - *huawei-bj-001
          - *huoshan-bj-001
        pgp:
          - *xiongchenyu
  - path_regex: secrets/[^/]+\.env$
    key_groups:
      - age:
          - *office
          - *mail
          - *game-office
          - *game
          - *netbird
          - *huawei-bj-001
          - *huoshan-bj-001
        pgp:
          - *xiongchenyu
