#zsh plugins
[alias-tips]
src.git = "https://github.com/djui/alias-tips.git"
fetch.git = "https://github.com/djui/alias-tips.git"

[wakatime-zsh-plugin]
src.git = "https://github.com/sobolevn/wakatime-zsh-plugin.git"
fetch.git = "https://github.com/sobolevn/wakatime-zsh-plugin.git"
