# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }: {
  alias-tips = {
    pname = "alias-tips";
    version = "cd13ef223c4f310d774cdf8cb0435474cc2bcbbe";
    src = fetchgit {
      url = "https://github.com/djui/alias-tips.git";
      rev = "cd13ef223c4f310d774cdf8cb0435474cc2bcbbe";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-fDYAJSJHatxHhAT68AH4PuIHdwxFXipAoDHITVpkkkE=";
    };
  };
  wakatime-zsh-plugin = {
    pname = "wakatime-zsh-plugin";
    version = "69c6028b0c8f72e2afcfa5135b1af29afb49764a";
    src = fetchgit {
      url = "https://github.com/sobolevn/wakatime-zsh-plugin.git";
      rev = "69c6028b0c8f72e2afcfa5135b1af29afb49764a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-pA1VOkzbHQjmcI2skzB/OP5pXn8CFUz5Ok/GLC6KKXQ=";
    };
  };
}
