[singbox_servers]
lubancat ansible_host=203.116.95.146 ansible_user=cat
sg-office ansible_host=101.78.126.6 ansible_user=root ansible_become=false

[singbox_legacy]
ubuntu-server ansible_host=45.194.18.75 ansible_user=root ansible_ssh_common_args='-o StrictHostKeyChecking=no'
