# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/94fa1b47-d40e-49da-92e8-87b689ed0b5b";
    fsType = "btrfs";
    options = [ "subvol=@" "compress=zstd" ];
  };

  boot.initrd.luks.devices."enc".device =
    "/dev/disk/by-uuid/4778a4f5-c8e4-46d1-bbfa-f4d2aea80b09";

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/94fa1b47-d40e-49da-92e8-87b689ed0b5b";
    fsType = "btrfs";
    options = [ "subvol=@home" "compress=zstd" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/94fa1b47-d40e-49da-92e8-87b689ed0b5b";
    fsType = "btrfs";
    options = [ "subvol=@nix" "compress=zstd" "noatime" ];
  };

  fileSystems."/etc" = {
    device = "/dev/disk/by-uuid/94fa1b47-d40e-49da-92e8-87b689ed0b5b";
    fsType = "btrfs";
    options = [ "subvol=@etc" "compress=zstd" ];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/94fa1b47-d40e-49da-92e8-87b689ed0b5b";
    fsType = "btrfs";
    options = [ "subvol=@persist" "compress=zstd" ];
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/0E95-3DFB";
    fsType = "vfat";
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  # hardware.video.hidpi.enable = lib.mkDefault true;
}
