addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "latest.integration")
addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "latest.integration")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "latest.integration")
addSbtPlugin("com.orrsella" % "sbt-stats" % "latest.integration")
addSbtPlugin("io.spray"        % "sbt-revolver" % "latest.integration")
