# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  bttc = {
    pname = "bttc";
    version = "v1.0.2";
    src = fetchFromGitHub ({
      owner = "bttcprotocol";
      repo = "bttc";
      rev = "v1.0.2";
      fetchSubmodules = true;
      sha256 = "sha256-qptNGs6NmbIEzmosASAvdZSIUhw5RVcgEF55/RhgR3I=";
    });
  };
  delivery = {
    pname = "delivery";
    version = "v1.0.2";
    src = fetchFromGitHub ({
      owner = "bttcprotocol";
      repo = "delivery";
      rev = "v1.0.2";
      fetchSubmodules = true;
      sha256 = "sha256-HItF37qlIm6IT8WSomTulkX7524UZwpwMbqyjckXFxA=";
    });
  };
  my_cookies = {
    pname = "my_cookies";
    version = "0.1.3";
    src = fetchurl {
      url = "https://pypi.io/packages/source/m/my_cookies/my_cookies-0.1.3.tar.gz";
      sha256 = "sha256-3e5j0HFOXUyUo6YVUKQnbaxvAUtDoRTzGqW8HUfzrQ8=";
    };
  };
}
